server.port=8888
spring.application.name=config-server

# Seguridad del Config Server
spring.security.user.name=configuser
spring.security.user.password=configpass123

# Ubicacion de los archivos de configuracion
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true